binutils: remove harmful binutils installation at /usr/TRIPLE
This causes "no" being prefixed to search directories when ld discovers
a new dependency when linking to a shared library:

libm.so.6 needed by /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so
attempt to open no/usr/x86_64-aosc-linux-gnu/lib64/libm.so.6 failed
attempt to open no/usr/local/lib64/libm.so.6 failed
attempt to open no/lib64/libm.so.6 failed
attempt to open no/usr/lib64/libm.so.6 failed
attempt to open no/usr/x86_64-aosc-linux-gnu/lib/libm.so.6 failed
attempt to open no/usr/local/lib/libm.so.6 failed
attempt to open no/lib/libm.so.6 failed
attempt to open no/usr/lib/libm.so.6 failed
attempt to open no/usr/x86_64-aosc-linux-gnu/lib64/libm.so.6 failed
attempt to open no/usr/local/lib64/libm.so.6 failed
attempt to open no/lib64/libm.so.6 failed
attempt to open no/usr/lib64/libm.so.6 failed
attempt to open no/usr/x86_64-aosc-linux-gnu/lib/libm.so.6 failed
attempt to open no/usr/local/lib/libm.so.6 failed
attempt to open no/lib/libm.so.6 failed
attempt to open no/usr/lib/libm.so.6 failed
/usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../x86_64-aosc-linux-gnu/bin/ld: warning: libm.so.6, needed by /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so, not found (try using -rpath or -rpath-link)
ld-linux-x86-64.so.2 needed by /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so
found ld-linux-x86-64.so.2 at /usr/lib/ld-linux-x86-64.so.2
libgcc_s.so.1 needed by /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so
found libgcc_s.so.1 at /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libgcc_s.so.1
/usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../x86_64-aosc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
/usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../x86_64-aosc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so: undefined reference to `fesetround@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../x86_64-aosc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../lib64/libstdc++.so: undefined reference to `fegetround@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-aosc-linux-gnu/15.2.0/../../../../x86_64-aosc-linux-gnu/bin/ld: link errors found, deleting executable `test'
collect2: error: ld returned 1 exit status